# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  xenon_config = debug
  game_config = debug
endif
ifeq ($(config),release)
  xenon_config = release
  game_config = release
endif

PROJECTS := xenon game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

xenon:
ifneq (,$(xenon_config))
	@echo "==== Building xenon ($(xenon_config)) ===="
	@${MAKE} --no-print-directory -C . -f xenon.make config=$(xenon_config)
endif

game: xenon
ifneq (,$(game_config))
	@echo "==== Building game ($(game_config)) ===="
	@${MAKE} --no-print-directory -C . -f game.make config=$(game_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f xenon.make clean
	@${MAKE} --no-print-directory -C . -f game.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   xenon"
	@echo "   game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"