#pragma once
#define ASPECT_RATIO 0.75

#define WND_WIDTH 1080
#define WND_HEIGHT WND_WIDTH * ASPECT_RATIO

#define VIRTUAL_WIDTH 400
#define VIRTUAL_HEIGHT VIRTUAL_WIDTH * ASPECT_RATIO

#define BACKGROUND_COLOR Color::RGB(220, 220, 220)